---
title: "Getting started with SGP"
author: "Damian W Betebenner & Adam R Van Iwaarden"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Getting started with SGP}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---

```{r include = FALSE}
    library(SGP)
    library(SGPdata)

    is_html_output = function() {
        knitr::opts_knit$get("rmarkdown.pandoc.to")=="html"
    }

    knitr::opts_chunk$set(
        collapse=TRUE,
        comment="",
        prompt=TRUE,
        fig.dpi=96)

    if (is_html_output()) {
        options(width=1000)
    }
```

# Introduction

The **SGP** Package is open source software built for the [**R** software environment](https://www.r-project.org/). The classes, functions and data within the
**SGP** package are used to calculate student growth percentiles and percentile growth projections/trajectories using large scale, longitudinal assessment data. Quantile regression is used to estimate the conditional density associated with each student's achievement history. Percentile growth projections/trajectories are calculated using the derived coefficient matrices and show the percentile growth needed to reach future achievement targets.

The **SGP** package was first released, October 17th, 2008. The package is under [active development on GitHub](https://github.com/CenterForAssessment/SGP) by
[Damian Betebenner](https://github.com/dbetebenner) and [Adam Van Iwaarden](https://github.com/adamvi). Being a package built for the
[**R** software environment](https://www.r-project.org/), to use the **SGP** one needs a computer with **R** installed. **R** is available
for Window, OSX, and Linux and, being open source, can be compiled for just about any operating system.

Analyses using the **SGP** are designed to be performed (broadly) in a simple two step process:

1. [Data preparation](SGP_Data_Preparation.html)
2. [Data analyses](SGP_Data_Analysis.html)

Like with all data analysis, the bulk (> 90%) of the time is spent on data preparation. Once data is prepared correctly, analyses conducted using the **SGP** are intended
to be simple and straightforward. Analyses that we assist on all follow this two step process.

# Software and Hardware Requirements





# Data Preparation: Wide or Long Data

There a two formats for representing longitudinal (time dependent) student assessment data: WIDE and LONG format. For WIDE format data, each case/row
represents a unique student and columns represent variables associated with the student at different times. For LONG format data, time dependent
data for the student is spread out across multiple rows in the data set. The [SGPdata Package](https://github.com/CenterForAssessment/SGPdata), installed
when one installs the [SGP Package](https://github.com/CenterForAssessment/SGP), includes exemplar WIDE and LONG data sets (sgpData and sgpData_LONG, respectively)
to assist in setting up your data.

In general, the lower level functions in the SGP package that do the calculations, ```studentGrowthPercentiles``` and ```studentGrowthProjections``` require WIDE formatted
data whereas the higher level functions that are built toward operational analyses require LONG data. If running anything but the basic analyses, we recommend setting
up your data in the LONG format as much of the capability of the package is built around the user supplying data in that way.




# Data Analysis


# Advanced SGP Analysis


# Contributions & Requests

If you have a topic for an **SGP** vignette that you'd like to see, don't hesitate to write or set up an
[issue on GitHub](https://github.com/CenterForAssessment/SGPdata/issues).
